[package]
name = "solana_bulk_transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
solana-client = "1.18.0"
solana-sdk = "1.18.0"
futures = "0.3"
